### ISSUE TITLE
Partial update

### ISSUE THREAD

**Issue by Lefort-Antoine** [openergy/omemdb#3]
Due to the size of the db, I would like to ba able to load a part of the model from an import. I could be use to complete the db or to update it.

Supposing 
```
import os
from omemdb.packages.omarsh import Schema, fields
from omemdb import Record, Db, LinkField, TupleLinkField 

class Model1(Record):
    class Schema(Schema): 
        ref = fields.String(required=True)
        p1 = fields.Float(missing=None)
        m2 = LinkField("Model2", missing=None)
        
class Model2(Record):
    class Schema(Schema): 
        ref = fields.String(required=True)
        adress = fields.String(missing=None)
        lat = fields.Float(missing=None)
        lon = fields.Float(missing=None)
    
class AppBuildingDb(Db):
    models = [
        Model1,
        Model2
    ]
```

Case 1 - How to combine the db : db1 and db2 ?
```
db1 = AppBuildingDb()

db1.model2.batch_add((dict(ref=f"z{z_i}") for z_i in range(2)))

for z_i in range(2):
    # create surfaces
    db1.model1.add(
        ref=f"s{z_i}",
        m2=f"z{z_i}",
        p1=12
    )
        
db2 = AppBuildingDb()

db2.model2.batch_add((dict(ref=f"a{z_i}") for z_i in range(2)))

for z_i in range(2):
    # create surfaces
    db2.model1.add(
        ref=f"b{z_i}",
        m2=f"a{z_i}",
        p1=22
    )
        
```

Case 2 - How to update db1 ?
```

db = AppBuildingDb()

# create zones (batch)
db.model2.batch_add((dict(ref=f"z{z_i}") for z_i in range(3)))

for z_i in range(3):
    # create surfaces
    db.model1.add(
        ref=f"s{z_i}",
        m2=f"z{z_i}",
        p1=55
    )
        
# partials models to update
## from other db
dbpartial = AppBuildingDb()
dbpartial.model2.add(ref="z0", adress="new adress")

## from dict or json
model2_dict = dict(ref="z0", adress="new adress")

```

I find this way but I think is not proper:
```
m2_to_update = db.model2.one("z0")
for k,v in model2_dict.items():
    setattr(m2, k, v)
```

Thanks for help !

**Comment by Lefort-Antoine** [comment]
Hy,
In the case 2 the idea is to update `db.model2.one("z0")` with the attribut of the `model2_dict ` or the `dbpartial.model2.one("z0")`.
The underlying idea of merge two databases is the need of working one databases parts independently. 
Maybe you can provide me a better way to do that? if not, what can you propose me some guideline to merge my databases ?
Regards,

**Comment by ccruveiller** [comment]
Hi for combining two databases (supposing they have same tables) I would combine it first in json_data and then create the combined db from this new json data (duplicates are not handled) 

db1_data = db1.to_json_data()
db2_data = db2.to_json_data()
for k,items in db1_data.items():
    if items is not None:
        db2_data[k].extend(items)

db = AppBuildingDb(json_data=db2_data)


For case 2 you could do
 if its from json:
db.model2.one("z0").update(data = model2_dict)
if its from other model:
db.model2.one("z0").update(data = dbpartial.model2.one("z0").to_json_data())

Hope its what you were looking for ! :)

**Comment by Lefort-Antoine** [comment]
Thanks !
